export const SET_WISHES = 'SET_WISHES';
export const SET_WISH_BY_ID = 'SET_WISH_BY_ID';
export const SET_TEMPLATES = 'SET_TEMPLATES';
export const SET_SELECTED_WISH = 'SET_SELECTED_WISH';
export const SET_SELECTED_TEMPLATE = 'SET_SELECTED_TEMPLATE';